Update WaveSlider.kt to fix java.lang.NoSuchMethodError
Google developers just updated androidx.compose.material3 to 1.2.0:alpha-08, this update includes many changes that affect this library, such as migrating from sliderPositions to sliderState and making sliderPositions.tickFractions internal, so I made an updated version of WaveSlider.kt to fix the errors caused by these changes.